JuliaCI/PkgTemplates.jl

Project.toml

The difference almost murdered my brain today by loading two versions of PkgTemplates in the same session.

Fix UUID to match registry

---

Project.toml
src/PkgTemplates.jl
src/plugin.jl
src/plugins/coveralls.jl
src/plugins/documenter.jl
src/plugins/githubpages.jl
src/plugins/travisci.jl
src/template.jl
test/interactive/interactive.jl
test/tests.jl

Way back TerminalMenus.jl didn't work in Travis OSX tests, but apparently it's all good now. Also realized that using `@spawn` instead of `@async` is kind of useless.

Don't skip interactive mode tests on MacOS

---

README.md
docs/src/index.md
docs/src/pages/plugins.md
src/PkgTemplates.jl
src/generate.jl
src/plugins/codecov.jl
test/interactive/plugins.jl
test/plugins/appveyor.jl
test/plugins/codecov.jl
test/plugins/travisci.jl
test/tests.jl

I never realized that it was spelled wrong the whole time... 
I'm not sure if this is actually worth it tbh but I do like keeping things accurate.

Deprecate CodeCov for Codecov

---

Manifest.toml
Project.toml
REQUIRE
src/PkgTemplates.jl
src/plugin.jl
src/plugins/appveyor.jl
src/plugins/codecov.jl
src/plugins/coveralls.jl
src/plugins/documenter.jl
src/plugins/githubpages.jl
src/plugins/gitlabci.jl
src/plugins/travisci.jl
src/template.jl
test/tests.jl

I don't precisely remember why we needed AutoHashEquals (I think maybe Julia v0.x didn't implement `hash`, which `Dict` keys require, for new structs), but one test did still depend on it. Regardless, it's not needed anymore.
Other changes:
- Make struct fields concrete (mostly `AbstractString` -> `String`)
- Replace some big interpolated expressions with the varargs form of `print`

Drop AutoHashEquals dependency, other minor updates

---

docs/src/index.md

Closes #49 
The examples run in a new environment since they create new packages, but PkgTemplates wasn't installed in it.

Fix code loading in documentation generation

---

src/plugins/githubpages.jl
test/plugins/githubpages.jl

It seems Documenter.jl changed the setting:
https://juliadocs.github.io/Documenter.jl/v0.21/lib/public/#Documenter.deploydocs

Use "dev" instead of "latest" to link GitHub pages

---

defaults/gitlab-ci.yml
docs/src/pages/plugins.md
src/PkgTemplates.jl
src/plugins/gitlabpages.jl
test/plugins/gitlabpages.jl
test/tests.jl

I was playing with GitLab pages and thought it would be nice if PkgTemplates can do what it does with `GitHubPages` plugin for GitHub.  So, this is my WIP try on implementing it.
I noticed that it's not straightforward to implement versioned documentation deploy like Documenter.jl does in Travis because it's coupled with how GitHub pages work (I think).  So, at the moment my PR only supports publishing `dev` (latest) documentation.  But I think the URL would be forward-compatible even after Documenter.jl supports GitLab CI.  So, before adding tests for it, I'd like know the feasibility for this PR to be merged even without versioned documentation support as in GitHub.
TODO:

Add GitLabPages plugin

---

licenses/EUPL-1.2+
src/licenses.jl

Add the [European Union Public Licence v1.2](https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12) to the templates.
---
Since this licence exists and is valid in 22 languages, and devs can choose their preferred one, I'd also like to add those versions. (mostly because I also need the German version in addition to the English one for some of my own projects and it'd make my life easier 😛)
However, it would blow up the interactive prompt, so I decided against it. If you have a suggestion on how to get around that issue, I'd implement it and submit another PR.

Add EUPL-1.2+ (EN) license

---

src/generate.jl

This partially reverts commit 8a1b65a34a43ee80ae868ec4c2775a716f9b8352 from #56.
see: https://discourse.julialang.org/t/22677/22

Revert "Use METADATA-compatible UUIDs"

---

src/PkgTemplates.jl
src/generate.jl
src/plugins/citation.jl
src/template.jl
test/plugins/citation.jl
test/tests.jl

Since the Julia community is starting to agree on a standardized CITATION.bib file, it would be great to be able to have it from PkkTemplates

Add CITATION.bib

---

defaults/drone.yml
src/PkgTemplates.jl
src/plugins/droneci.jl
test/plugins/droneci.jl
test/tests.jl

Fix #93.  I went with the easiest solution of just generating `.drone.yml` without the Jsonnet file.
I hope I didn't mess things up, I mostly just copied whatever was there for Cirrus and replace "cirrus" ->  "drone" :stuck_out_tongue:

Add Drone CI plugin

---

.travis.yml

FFTW, is required by something in ReferenceTests, and its build seems to either hang or just take a long time on Windows in Julia 1.0. 
Example: https://travis-ci.org/invenia/PkgTemplates.jl/jobs/609854008

Allow failures for Windows on 1.0

---

Project.toml

As per
https://white.ucc.asn.au/2019/09/28/Continuous-Delivery-For-Julia-Packages.html#what-if-i-dont-want-to-release-right-now--dev-versions
and inline with how Julia itself uses `-DEV`

Correct verision string to indicate this is unreleased

---

src/plugins/ci.jl

the link and image urls are backwards.

Fix broken GH Actions badge

---

src/PkgTemplates.jl
src/deprecated.jl

This should take care of the most common undefined methods that people will run into.
The `interactive` ones don't actually have an implementation beneath them yet, but they don't throw errors.
Unrelated, I think I can avoid changing the reference test manifests by mocking `Pkg.add(::PackageSpec)`, but it only worked on 1.3. Eventually these files won't need constant updates.

Add deprecations of old exports

---

defaults/travis.yml

* These are aliases in travis, and defining them twice causes one to
overwrite the other.  In this case, `matrix` was overwriting `jobs`,
which caused `Documentation` not to run.
Fixes #132
Note: this targets the current release branch, not master.  It's already been fixed on master, so this is meant as a stop-gap fix until master is release.

Merge `matrix:` and `jobs:` sections in .travis.yml

---

.travis.yml
templates/github/workflows/ci.yml
templates/gitlab-ci.yml
templates/travis.yml
test/fixtures/AllPlugins/.gitlab-ci.yml
test/fixtures/AllPlugins/.travis.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/WackyOptions/.gitlab-ci.yml
test/fixtures/WackyOptions/docs/Manifest.toml

Allows for Julia code to not require the use of semi-colon which is matches how most users will write Julia code. An additional benefit is that it allows for use of single line comments.

Use literal block style for multi-line YAML

---

templates/gitlab-ci.yml
test/fixtures/AllPlugins/.gitlab-ci.yml
test/fixtures/WackyOptions/.gitlab-ci.yml

Use GitLab CI's [`extends`](https://docs.gitlab.com/ee/ci/yaml/#extends) instead of YAML anchors. The `extends` is a bit more flexible and the syntax is a bit cleaner.
Note this change will conflict with #131.

Switch to using GitLab CI extends

---

.travis.yml
docs/Manifest.toml
docs/Project.toml

I just noticed that PkgTemplates wasn't included in the docs/Project.toml which is required in Julia 1.3.

Test documentation on latest Julia release

---

Manifest.toml
docs/Manifest.toml
src/plugins/documenter.jl
test/fixtures/WackyOptions/docs/Manifest.toml

Part 2 of #139 
Is this (`dev ..`) the right thing to do here? It seems legit but I'm not quite sure.

Pkg.develop new packages in the Documenter manifest

---

src/template.jl

closes #152 
Also make "contributors" the default when the user name isn't known.

default authors: add "and contributors" (close #152)

---

src/PkgTemplates.jl
src/plugins/git.jl
test/git.jl
test/show.jl

Closes #149 
Now no global Git configuration is strictly required via `Template(; plugins=[Git(; name="me", email="a@b.c")])`

Git: Allow setting custom user.name and user.email

---

src/plugin.jl
src/plugins/ci.jl
src/plugins/citation.jl
src/plugins/compat_helper.jl
src/plugins/coverage.jl
src/plugins/license.jl
src/plugins/readme.jl
src/plugins/src_dir.jl
src/plugins/tagbot.jl
src/plugins/tests.jl
test/plugin.jl

The new name does a much better job of describing what they're actually for, IMO.
One thing I wish we could do is deprecate `BasicPlugin` in a way that triggers the warning when it's subtyped, but I don't think that's possible.

Rename BasicPlugin -> FilePlugin

---

Project.toml
docs/src/developer.md
test/reference.jl
test/runtests.jl
test/show.jl

ReferenceTests has a bunch of image-specific stuff that we don't care
about, and building it (or rather, its dependencies) sometimes chokes the CI.
This way, we also get interactive prompts when running Pkg.test from the REPL,
and the `show` tests display nice diffs now, too.

Replace ReferenceTests with our own function

---

Project.toml
src/plugins/git.jl
test/git.jl
test/show.jl

Had a nice conversation with @aminya who is looking at PkgTemplates for non-Julia stuff. All the Julia-specific plugins can be disabled easily, but Git only requires this small change to be language-agnostic.

Make the .jl remote suffix optional

---

templates/appveyor.yml
templates/cirrus.yml
templates/github/workflows/ci.yml
templates/travis.yml
test/fixtures/AllPlugins/.appveyor.yml
test/fixtures/AllPlugins/.cirrus.yml
test/fixtures/AllPlugins/.github/workflows/ci.yml
test/fixtures/AllPlugins/.travis.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/WackyOptions/.appveyor.yml
test/fixtures/WackyOptions/.cirrus.yml
test/fixtures/WackyOptions/.github/workflows/ci.yml
test/fixtures/WackyOptions/.travis.yml

Closes #166
I've tested Travis, AppVeyor, and GHA, but I couldn't get Cirrus to pick up on my repo for some reason. According to the docs it should work.
GitLab doesn't allow caching files outside of the repository directory, so caching can't be used there. DroneCI's caching looks a bit more complicated so maybe I'll look at it another day, it's not used frequently anyways.

Cache artifacts in Travis, AppVeyor, GitHubActions, and Cirrus

---

templates/github/workflows/ci.yml
templates/travis.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/DocumenterTravis/.travis.yml

This was kind of mentioned during #139, I think it's probably safer these days to use the latest Julia. It's more likely that a package fails to load on 1.0 than on latest 1.x, I think. Also I think 1.0 was chosen back when plain 1 wasn't a thing.

Use Julia 1.x for doc builds on Travis and GHA

---

templates/github/workflows/ci.yml
test/fixtures/AllPlugins/.github/workflows/ci.yml

The first commit uses the codecov action (https://github.com/codecov/codecov-action) which @SaschaMann recommended to me (pointing to https://github.com/uva-bi-sdad/COVID_Tracking_Clean/blob/master/.github/workflows/ci.yml#L64-L70) when I was having issues with codecov mixing up which branch was which. One nice thing about it is that a token is not required for public repos.
The second commit is a bit more opinionated (and I understand if you don't want to include it) and runs CI only on pushes or PRs to the master branch, and ignores changes to the license, readme, and CompatHelper and Tagbot actions. I end up almost always wanting this in my repos, especially since github actions don't autocancel (so push a few commits and then make a PR, and CI doesn't run on the PR for awhile since it …

Update Github actions CI

---

src/interactive.jl
src/plugins/ci.jl
test/interactive.jl

Closes #183
Closes #184
There's a slight behaviour change here but I think it's for the better: if a user enters `MAJOR.MINOR.PATCH` in `extra_versions`, then the full version number with patch shows up in the file. Previously it would just be `MAJOR.MINOR`. Defaults however are not changed. We also support version ranges now too, which GitHub Actions supports.

Make extra_versions accept any string, strip quotes from input

---

templates/github/workflows/ci.yml
templates/gitlab-ci.yml
templates/travis.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/WackyOptions/.gitlab-ci.yml

Currently, if doctests are failing, the CI job will still pass, which means that it is easy to doctest failures to fly under the radar.
This PR runs the doctests by default in a step that will fail the CI job if the doctests fail.

Documenter: run doctests by default

---

templates/github/workflows/CompatHelper.yml

This pull request makes the following changes:
1. Use the `DOCUMENTER_KEY` SSH deploy key by default.
2. Enables the `workflow_dispatch` trigger.
cc: @christopher-dG 
cc: @timholy

CompatHelper: by default, use the `DOCUMENTER_KEY` SSH deploy key

---

src/plugins/tagbot.jl

Fixes #206 
cc: @christopher-dG 
h/t @timholy for having this idea originally in #162

TagBot: use the `DOCUMENTER_KEY` SSH deploy key by default

---

src/plugin.jl
test/show.jl

currently, if a system image is compiled that contains PkgTemplates, the `Template` functionality won't be redistributable, since it is using a global constant that get evaluated to be a very specific path on the build machine but not the user's actual path during compilation. Then you maybe get something like MIT license not found error.
since TEMPLATES_DIR is only used for `default_files` I think it's OK to just use `pathof`.

use dynamic path to make sysimg happy

---

.github/workflows/ci.yml

Fast failures often make it impossible to figure out which jobs are actually passing.

GitHub Actions CI for the PkgTemplates.jl repo: Disable fast failures

---

templates/github/workflows/ci.yml
test/fixtures/AllPlugins/.github/workflows/ci.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/WackyOptions/.github/workflows/ci.yml

Currently, the job names look like this:
```
CI / Julia 1.0 - ubuntu-latest - x64
```
Suppose that I mark the `CI / Julia 1.0 - ubuntu-latest - x64` job as "required" in the GitHub protected branch settings.
This requirement will be matched by both "push" and "pull request" builds.
However, when users mark CI jobs as required in the protected branch settings, the implication is usually that they are referring to the pull request builds. Pull request builds are testing the merge commit that would result from merging the PR into `master`. In contrast, push builds are testing the head commit.
The problem with the current job names is that protected branch settings cannot distinguish between "push" and "pull request" builds.
After this PR, the job names look like this:
```
CI / Julia 1.0 - …
```

Template for GitHub Actions CI: More descriptive job names

---

src/plugins/git.jl

Turns out that some of the fiddling I was doing with the Git remote was actually creating a subtly invalid config that I only discovered when I tried to run `LibGit2.remote_delete` on it. By taking away that fiddling, we end up with exactly what you get after running `git remote add origin <url>`.

Don't bork the remote config

---

templates/github/workflows/ci.yml
test/fixtures/AllPlugins/.github/workflows/ci.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/WackyOptions/.github/workflows/ci.yml

I'm not too familiar with this repo, are there other places where this needs to be changed that I missed?

GHA: Don't use potentially breaking version tags

---

Project.toml
docs/make.jl
templates/docs/make.jl
test/fixtures/AllPlugins/docs/make.jl
test/fixtures/DocumenterGitHubActions/docs/make.jl
test/fixtures/DocumenterTravis/docs/make.jl
test/fixtures/WackyOptions/docs/make.jl

i don't know how to explain this one... this `L` has been here a long time, but it seems unnecessary as it always results in URLs like `https://github.com/etc..../foo.jl#LL1-2` with the double `LL`. Here's an example result of this change:
```diff
-https://github.com/invenia/PkgTemplates.jl/blob/89e6dd5e39641c8d40b2492d307e361a83b6dd0f/src/plugin.jl#LL155-L162
+https://github.com/invenia/PkgTemplates.jl/blob/89e6dd5e39641c8d40b2492d307e361a83b6dd0f/src/plugin.jl#L155-L162
```
I tested with Documenter 0.23, 0.24 and 0.25 and it always gives this same `LL` result. 
As you can test for yourself using the two example links above, both work i.e. both link correctly to the source code of the `PkgTemplates.tags(::Plugin)` function.
However, the `LL` doesn't (or doesn't any longer??) work on …

Remove `L` prefix before line segment of repo URL

---

src/plugin.jl

this follows #209  the current implementation is still not relocatable - the directory PkgTemplate may not exist if it is compiled into the system image, so one way to get rid of it is to allow reset some of the default paths to new places.

allow changing default template dir

---

Project.toml
src/plugins/documenter.jl
src/plugins/readme.jl
test/show.jl

This PR includes a couple of small changes to make plugins more easily customizable, particularly the printing of badges in the README.
First, I have dropped the restriction to `DeployStyle` from the type parameter of `Documenter`.  The reason for this is that, as `DeployStyle` is a type union, a user cannot create a new plugin type and provide it as a type parameter to `Documenter`.  This is needed to, e.g. change the badges returned by the `Documenter` plugin.
Next, I have added the `badge_order::Vector{DataType}` field to the `Readme` struct.  This allows users to set their own badge order.  The original default order remains the default, but I have changed the name of the function that creates this order to `default_badge_order` for clarity.
I don't think there should be any test …

some changes to allow for more customization of badges

---

src/plugins/documenter.jl
test/plugin.jl

Fixes this bug we noticed with our package template extensions:
```
MethodError: no method matching isless(::Symbol, ::Bool)
Closest candidates are:
isless(!Matched::Missing, ::Any) at missing.jl:87
isless(::Symbol, !Matched::Symbol) at strings/basic.jl:341
isless(!Matched::AbstractFloat, ::Real) at operators.jl:167
...
Stacktrace:
[1] isless(::Pair{Symbol,Any}, ::Pair{Symbol,Any}) at ./pair.jl:57
[2] lt at ./ordering.jl:57 [inlined]
[3] sort!(::Array{Pair{Symbol,Any},1}, ::Int64, ::Int64, ::Base.Sort.InsertionSortAlg, ::Base.Order.ForwardOrdering) at ./sort.jl:498
[4] sort!(::Array{Pair{Symbol,Any},1}, ::Int64, ::Int64, ::Base.Sort.MergeSortAlg, ::Base.Order.ForwardOrdering, ::Array{Pair{Symbol,Any},1}) at ./sort.jl:583
[5] sort! at ./sort.jl:582 [inlined]
[6] sort! at ./sort.jl:673 …
```

Fix Documenter plugin sort bug

---

src/PkgTemplates.jl

I use PkgTemplates just infrequently enough that I forget how to use it every time. This adds a shortened version of the README usage as a module docstring.

Add a module docstring

---

.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

Fixes CI failures introduced in #304 
Also brings this repo's own CI in line with the #304 change.

Fix CI failures from #304

---

Project.toml
docs/src/developer.md
templates/github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

This switches the default GHA + Documenter config to use the julia-docdeploy action in order to take advantage of the new in-line annotation feature: https://github.com/julia-actions/julia-docdeploy/releases/tag/v1.2.0.
Uses `buildpkg` to build while avoiding the package server (and also to follow the julia-docdeploy README example).

use `julia-docdeploy` action

---

Project.toml
templates/licenses/LGPL-3.0+

Fixes #330
This pull request fixes the license text for LGPL 3.0+ so that it exactly matches the license text from the GNU website (https://www.gnu.org/licenses/lgpl-3.0.txt).
Here are the commands used to generate this PR:
```
git clone https://github.com/invenia/PkgTemplates.jl.git
cd PkgTemplates.jl
git checkout master
git checkout -B dpa/fix-lgpl-license-text
rm templates/licenses/LGPL-3.0+
mkdir -p templates/licenses
curl -o templates/licenses/LGPL-3.0+ https://www.gnu.org/licenses/lgpl-3.0.txt
git add templates/licenses/LGPL-3.0+
git commit -m "Fix the license text for LGPL 3.0+"
git remote rm origin
git remote add myfork git@github.com:DilumAluthge/PkgTemplates.jl.git
git push -f myfork dpa/fix-lgpl-license-text
```

Fix the license text for LGPL 3.0+

---

Project.toml
templates/github/workflows/CI.yml
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

See https://github.com/marketplace/actions/cache-julia-artifacts-packages-and-registry
This action caches artifacts and packages and hides the actual config similar to julia-runtest and julia-buildpkg. If a Julia update will require a change to the cache config, people using the template workflow won't have to manually go and fix it everywhere.
The action has options to disable caching of either packages and artifacts and to enable caching of registries, which may be worth considering as an option given to the user via the PkgTemplates interface.

GHA: Use julia-actions/cache action

---

.github/workflows/CI.yml
src/plugins/project_file.jl
src/plugins/tests.jl
test/fixtures/AllPlugins/.appveyor.yml
test/fixtures/AllPlugins/.cirrus.yml
test/fixtures/AllPlugins/.drone.star
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/AllPlugins/.gitlab-ci.yml
test/fixtures/AllPlugins/.travis.yml
test/fixtures/AllPlugins/Project.toml
test/fixtures/AllPlugins/docs/Manifest.toml
test/fixtures/Basic/Project.toml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/Project.toml
test/fixtures/DocumenterGitHubActions/docs/Manifest.toml
test/fixtures/DocumenterGitLabCI/.gitlab-ci.yml
test/fixtures/DocumenterGitLabCI/Project.toml
test/fixtures/DocumenterGitLabCI/docs/Manifest.toml
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/DocumenterTravis/Project.toml
test/fixtures/DocumenterTravis/docs/Manifest.toml
test/fixtures/WackyOptions/.github/workflows/CI.yml
test/fixtures/WackyOptions/Project.toml
test/fixtures/WackyOptions/docs/Manifest.toml
test/fixtures/WackyOptions/test/Manifest.toml
test/reference.jl
test/runtests.jl

In Julia 1.7, Project.toml generated by PkgTemplates is not compatible with Pkg's sort order.
```
(@v1.7) pkg> activate --temp
Activating new project at `/tmp/jl_ZsryYH`
julia> using PkgTemplates
│ Package PkgTemplates not found, but a package named PkgTemplates is available from a registry.
│ Install package?
│   (jl_ZsryYH) pkg> add PkgTemplates
└ (y/n) [y]:
...
(jl_ZsryYH) pkg> st
Status `/tmp/jl_ZsryYH/Project.toml`
[14b8a8f1] PkgTemplates v0.7.25
julia> Template(user = "tkf")("ExamplePackage")
[ Info: Running prehooks
...
[ Info: New package is at /home/arakaki/.julia/dev/ExamplePackage
shell> cd ~/.julia/dev/ExamplePackage
/home/arakaki/.julia/dev/ExamplePackage
shell> cat Project.toml
name = "ExamplePackage"
uuid = "db43d3c3-1afb-45d2-b722-e2cdd05cc17f"
authors = ["Takafumi Arakaki …
```

Generate Project.toml with Pkg's custom key order, and update reference tests to v1.7

---

.github/workflows/CompatHelper.yml
Project.toml
templates/github/workflows/CI.yml
templates/github/workflows/register.yml
test/fixtures/AllPlugins/.github/workflows/register.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/register.yml

Setting `permissions: contents: write` is required in new repositories for the `GITHUB_TOKEN` to work. See also https://github.com/JuliaDocs/Documenter.jl/pull/1819 and https://github.com/julia-actions/julia-docdeploy/pull/21
Without it, people might get an error like
```
fatal: unable to access 'https://github.com/rikhuijzer/MyProject.jl.git/': The requested URL returned error: 403
```
Please double-check whether I haven't missed a place in PkgTemplates.jl where this setting should be set too

Set `permissions: contents: write`

---

src/interactive.jl
src/plugins/documenter.jl
templates/docs/make.jl
test/fixtures/AllPlugins/docs/make.jl
test/fixtures/DocumenterGitHubActions/docs/make.jl
test/fixtures/DocumenterGitLabCI/docs/make.jl
test/fixtures/DocumenterTravis/docs/make.jl
test/fixtures/WackyOptions/docs/make.jl
test/interactive.jl
test/reference.jl

- close #348 
- Adds support for `edit_link` which was added in Documenter v0.24 (previously there was `edit_branch`) https://github.com/JuliaDocs/Documenter.jl/pull/1173
- since `edit_link=nothing` has a meaning in Documenter, we use `edit_link=:devbranch` to mean "do the obvious thing" which i think it is uncontroversial to say is "point at the main development branch" which we take from the `devbranch=...` keyword (which in turn fallsback to `default_branch(::Template)`)
- also adds support for users passing Symbols, both so we can use `:devbranch` as the default and because Documenter allows Symbols (specifically [the Symbol `:commit` has a special meaning](https://github.com/JuliaDocs/Documenter.jl/blob/8986c4d6e1b58ffc009f8b3733fc57520f4a73a9/src/Writers/HTMLWriter.jl#L307-L311))
cc …

Allow setting Documenter `edit_link`

---

src/interactive.jl
src/plugins/documenter.jl
src/template.jl
test/interactive.jl

- aims to close https://github.com/invenia/PkgTemplates.jl/issues/343 
- The first commit removes `String`  from the tips given at the prompt
-  Where before we had:
```Enter value for 'user' (String, required):```
we would now have just:
```Enter value for 'user' (required):```
- The second commit removes the quote marks `"` around default string values show in the prompt, because users don't need to use quotes when entering string values, and the third commit introduces a space to keep things easy to read
- Where before we had: 
```default="CompatHelper.yml"```
we would would now have:
```default: CompatHelper.yml```
Together this changes something like
```
Enter value for 'user' (String, default="nickrobinson251"):
```
to now be like
```
Enter value for 'user' (default: …
```

Improve display of tips and defaults in interactive prompt 

---

README.md
docs/make.jl
docs/src/developer.md
docs/src/index.md
docs/src/migrating.md
docs/src/user.md
src/plugins/license.jl
test/plugin.jl

Most of these redirected but it's good to update them anyways. Looks like docs got migrated without having to be regenerated, but Codecov will probably be empty until we have a successful test run.

Migrate links to JuliaCI/PkgTemplates.jl

---

templates/github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

This is needed to post the GitHub status with preview links, see [Documenter.jl documentation](https://documenter.juliadocs.org/dev/man/hosting/#GitHub-Actions).

Add `statuses: write` permission to GH token for docdeploy

---

test/runtests.jl

Work around for https://github.com/JuliaCI/PkgTemplates.jl/issues/370
I think this is fine for now since our reference tests also require running in Julia 1.7.2 anyway.

Only interactive tests pre-Julia 1.8

---

docs/src/user.md
src/template.jl
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/Basic/README.md
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/README.md
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/README.md
test/interactive.jl
test/show.jl
test/template.jl

Fixes https://github.com/JuliaCI/PkgTemplates.jl/issues/357

make GitHubActions a default plugin

---

src/plugins/documenter.jl
templates/github/workflows/CI.yml
templates/travis.yml
test/fixtures/AllPlugins/.gitignore
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.gitignore
test/fixtures/DocumenterGitLabCI/.gitignore
test/fixtures/DocumenterTravis/.gitignore
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.gitignore

The Documenter.jl docs say to dev the package before building the docs.
- https://github.com/JuliaDocs/Documenter.jl/blob/233a7822d670b063e894f62aea00729bcb3a28dd/docs/src/man/hosting.md?plain=1#L201-L202
The gitlab-ci script already does this, so this commit increases consistency.
This is also discussed in https://github.com/JuliaDocs/Documenter.jl/issues/1565 and https://discourse.julialang.org/t/documenter-jl-is-not-documenting-any-changes/94781/.
I also added `/docs/Manifest.toml` to the default `.gitignore`; this may be more controversial. I am happy to revert that.

github & travis: dev package before building docs

---

.github/workflows/CI.yml
.github/workflows/JuliaNightly.yml
templates/github/workflows/CI.yml
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

Current versions cause `Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, codecov/codecov-action@v2.` warnings.

Upgrade checkout and codecov action versions

---

docs/src/developer.md

Add a paragraph to the developer guide recommending local tests against Julia 1.7.2, otherwise the reference tests will not run and they are pretty essential.
I made the mistake myself and only discovered the test failure in the PR CI

Explain reference Julia version for tests

---

src/plugin.jl

It should be mentioned in the docs that `PkgTemplates` must be in scope for the `@plugin` macro to work:
```
using PkgTemplates: PkgTemplates, @with_kw_noshow, @plugin, Plugin
```
Otherwise some of the examples shown now do not work.
Fix #418.

plugin macro docs

---

Project.toml
src/plugins/tests.jl

Supersedes https://github.com/JuliaCI/PkgTemplates.jl/pull/367.
This PR closes:
* Fix https://github.com/JuliaCI/PkgTemplates.jl/issues/365.
* Fix https://github.com/JuliaCI/PkgTemplates.jl/issues/394.

Don't create empty Manifest.toml (v2)

---

Project.toml
src/plugins/git.jl
test/fixtures/WackyOptions/Manifest.toml

Follow-up to https://github.com/JuliaCI/PkgTemplates.jl/pull/425. The `Git` plugin was also `touch`ing an empty Manifest.toml which also triggered the warning. This fixes that.

Don't create empty Manifest.toml (again)

---

templates/github/workflows/CI.yml
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

A `workflow_dispatch` trigger for CI is useful, and is already present in the other workflow templates (e.g. `CompatHelper`, `TagBot`).

Add workflow_dispatch trigger to CI template

---

src/plugins/dependabot.jl
templates/github/workflows/CI.yml
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

A simple update of [`checkout`](https://github.com/actions/checkout) from v3 to v4.
As long as Dependabot is not used by default (#396) these often won't be updated after creation, so good to keep them up to date here.

update to actions/checkout@v4

---

src/plugins/tests.jl
templates/test/runtests.jl
test/fixtures/WackyOptions/test/Project.toml
test/fixtures/WackyOptions/test/runtests.jl
test/reference.jl
test/show.jl

Fix #416
@aviatesk can you take a look? I'm curious what you would recommend as the best "default" kwargs for JET in a package template

Add JET to Test plugin

---

Project.toml

https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958#update-november-2nd-2023-how-do-i-determine-what-the-compat-entry-should-be-for-a-stdlib-1

Add stdlib compat bounds

---

templates/github/workflows/CI.yml

See new perm requirements in https://github.com/julia-actions/cache/releases/tag/v1.4.0
Note that they're not mandatory, just that tidying up happens more efficiently if they are in place, and lowers the chance of a useful cache being auto-deleted by Github

Use CI caching for documentation job and add newly required perms

---

templates/licenses/AGPL-3.0+
templates/licenses/GPL-2.0+
templates/licenses/GPL-3.0+
templates/licenses/LGPL-2.1+
templates/licenses/LGPL-3.0+

The GNU licenses contain instructions for applying those licenses to works. They say that, ideally, folks should add a notice to each file. However, the template as was did not actually state that the works are licensed under the included license. This PR changes that by copying the recommended verbiage from each respective license.

Actually apply the GNU licenses

---

docs/make.jl
templates/docs/make.jl
test/fixtures/AllPlugins/docs/make.jl
test/fixtures/DocumenterGitHubActions/docs/make.jl
test/fixtures/DocumenterGitLabCI/docs/make.jl
test/fixtures/DocumenterTravis/docs/make.jl
test/fixtures/WackyOptions/docs/make.jl

Avoids the following warning by letting Documenter infer the repository instead of giving `repo::String`:
```julia
┌ Warning: Unable to determine the repository root URL for the navbar link.
│ This can happen when a string is passed to the `repo` keyword of `makedocs`.
│ 
│ To remove this warning, either pass a Remotes.Remote object to `repo` to completely
│ specify the remote repository, or explicitly set the remote URL by setting `repolink`
│ via `makedocs(format = HTML(repolink = "..."), ...)`.
└ @ Documenter.HTMLWriter ~/.julia/packages/Documenter/1HwWe/src/html/HTMLWriter.jl:707
```
The alternative would be to provide an explicit `Remotes.GitHub`, `Remotes.GitLab` or `Remotes.URL` depending on the host (see the release notes https://documenter.juliadocs.org/v1.0.0/release-notes/). …

Remove repo argument to makedocs

---

.github/workflows/CI.yml
test/fixtures/AllPlugins/.appveyor.yml
test/fixtures/AllPlugins/.cirrus.yml
test/fixtures/AllPlugins/.drone.star
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/AllPlugins/.gitlab-ci.yml
test/fixtures/AllPlugins/.travis.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.gitlab-ci.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml
test/fixtures/WackyOptions/Manifest.toml
test/runtests.jl

How I proceeded (might be useful for future updates)
1. change `test/runtests.jl` to run reference tests on v1.10.0
2. change `.github/workflows/CI.yml` to ensure that v1.10.0 is part of CI
3. go to `test/reference.jl`, comment out the following block and replace it with `copy_file(comparison, reference)`
```julia
if PROMPT
while true
println("Update reference file? [y/n]")
answer = lowercase(strip(readline()))
if startswith(answer, "y") || startswith(answer, "n")
startswith(answer, "y") && copy_file(comparison, reference)
break
end
end
end
```
4. run the tests
5. revert the changes to `test/reference.jl`

Run reference tests on 1.10 instead of 1.7

---

.github/workflows/CI.yml
src/plugins/ci.jl
src/template.jl
test/fixtures/AllPlugins/.appveyor.yml
test/fixtures/AllPlugins/.cirrus.yml
test/fixtures/AllPlugins/.drone.star
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/AllPlugins/.gitlab-ci.yml
test/fixtures/AllPlugins/.travis.yml
test/fixtures/AllPlugins/Project.toml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/Basic/Project.toml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/Project.toml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.gitlab-ci.yml
test/fixtures/DocumenterGitLabCI/Project.toml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/DocumenterTravis/Project.toml
test/fixtures/WackyOptions/.github/workflows/CI.yml
test/interactive.jl
test/show.jl

Most interesting changes:
- `src/template.jl`
- `src/plugins/ci.jl`
- `test/interactive`
- `test/show`
I still need advice on how to modify the interactive tests. For now we can only pick a 1.x.0, and it would be nice to have a default 1.6.7, right?

Switch default julia compat to 1.6.7

---

templates/github/workflows/CI.yml
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

I just noticed that the github action template still uses `julia-actions/setup-julia@v1`.  Bump that to v2.

github template: Bump julia-actions/setup-julia to v2

---

Project.toml
src/plugins/ci.jl
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml
test/show.jl

Partial fix for #474 
Changing the LTS is slightly more involved so let's start with avoiding nightly

Use "pre" instead of "nightly" for GitHub CI

---

templates/github/workflows/CI.yml
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

This seems unnecessary as the event is already shown in parantheses
alongside the job name. Having this in the job name causes issues when
using a merge queue as GitHub expects required jobs to have the same
name irrespective of being triggered by push/pr or by merge queue

GH Actions: remove event_name from job name

---

.github/workflows/CI.yml
test/fixtures/WackyOptions/Manifest.toml
test/reference.jl
test/runtests.jl

to disable the interactive prompt as it was somehow broken for me locally. Also bumps the Julia version for reference tests to 1.10.6

support JULIA_REFERENCETESTS_UPDATE env var in tests

---

.github/workflows/CI.yml

The company no longer exists, no one has checked that channel in years.

Delete Slack Notifier

---

src/plugins/tagbot.jl

Presumably an "or" was missing, thus changing the sense of the sentence into the opposite.

Edit TagBot docstring

---

Project.toml
src/plugins/tests.jl

The typo in interpolation of a variable name results in `UndefVarError: aqua_kwarg_names not defined in PkgTemplates` instead of desired explanation of the actual error

Typo in tests.jl

---

.github/workflows/CompatHelper.yml
templates/github/workflows/CompatHelper.yml
test/fixtures/AllPlugins/.github/workflows/CompatHelper.yml
test/fixtures/Basic/.github/workflows/CompatHelper.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CompatHelper.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CompatHelper.yml
test/fixtures/DocumenterTravis/.github/workflows/CompatHelper.yml
test/fixtures/WackyOptions/.github/workflows/CompatHelper.yml

- Use `shell:` option to launch julia directly
- Give each step a simpler name

Update CompatHelper.jl workflow files

---

src/plugins/citation.jl
templates/CITATION.bib
test/fixtures/WackyOptions/CITATION.bib

This PR fixes issue #389: "Version number in Citation plugin is hard-coded."
The version information is now obtained from the argument `t` in `view(::Citation, t::Template, pkg::AbstractString)`. For reference, here is a generated `CITATION.bib` file based on [this example](https://gist.github.com/ohno/f3b1eb2c8f3a7e6803c34c8aab56e869):
```
@misc{FewBodyHamiltonians.jl,
author  = {Shuhei Ohno, Martin Mikkelsen},
title   = {FewBodyHamiltonians.jl},
url     = {https://github.com/JuliaFewBody/FewBodyHamiltonians.jl},
version = {v0.0.1},
year    = {2025},
month   = {9}
}
```

Soft coding version number in Citation plugin (#389)
