Project.toml
src/PkgTemplates.jl
src/generate.jl
src/plugin.jl
src/plugins/coveralls.jl
src/plugins/documenter.jl
src/plugins/githubpages.jl
src/plugins/travisci.jl
src/template.jl
test/interactive/interactive.jl
test/tests.jl

On top of #35 to avoid some conflicts
Closes #37

Don't commit manifest by default 

---

defaults/travis.yml

Just a temporary fix until #23 is addressed.

Pin Documenter to v0.19

---

src/generate.jl

I know that this is kind of a bikeshedding, but let me request to sort lines in .gitignore.  I think it's better since it makes generated file more deterministic.

Request: Sort lines in .gitignore file

---

README.md
docs/src/index.md

First time user and I got hit with an error when I ran `t = Template()` because I didn't have `github.user` set and. The error only suggested passing an explicit argument to `Template`, so I think it would be good to clarify right away what it needs to work without arguments.

Clarify necessary Git options in docs

---

src/generate.jl

Add /dev/ to gitignore

---

src/template.jl

I wasn't sure what the `ssh` option did, hopefully this clarifies it a little.

clarify `ssh` option

---

docs/src/pages/package_generation.md
src/generate.jl
src/template.jl
test/runtests.jl
test/tests.jl

Ditch REQUIRE, add [compat]

---

Manifest.toml
README.md
defaults/cirrus.yml
docs/src/index.md
docs/src/pages/plugins.md
src/PkgTemplates.jl
src/plugins/cirrusci.jl
test/plugins/cirrusci.jl
test/tests.jl

Uses Alex's [CirrusCI.jl](https://github.com/ararslan/CirrusCI.jl). The first and third commits are the only relevant ones, the second is just some things I found along the way.

Add CirrusCI plugin for FreeBSD support

---

src/plugins/citation.jl

Fix interactive Citation

---

README.md

So people don't think this is the stable release since changes have been very significant and are still WIP

Add Notice to readme pointing to stable version

---

src/plugins/ci.jl
templates/github/workflows/ci.yml
test/fixtures/AllPlugins/.github/workflows/ci.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/WackyOptions/.github/workflows/ci.yml

Replaces #117, I just finished the last bit that needed to happen.

Add nightly Julia to GitHubActions plugin

---

.github/workflows/TagBot.yml
src/plugins/tagbot.jl
test/fixtures/AllPlugins/.github/workflows/TagBot.yml
test/fixtures/Basic/.github/workflows/TagBot.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/TagBot.yml
test/fixtures/DocumenterTravis/.github/workflows/TagBot.yml
test/show.jl

Mirrors https://github.com/JuliaRegistries/TagBot/pull/137.

Default to running TagBot daily

---

docs/src/migrating.md
docs/src/user.md
src/plugin.jl
src/template.jl
test/git.jl
test/template.jl

Closes #162, but needs some feedback first.
Before:
``` julia
t = Template(; plugins=[IWantThis()] disable_defaults=[IDontWantThis])
```
After:
``` julia
t = Template(; plugins=[IWantThis(), !IDontWantThis])
```

Add new negated-type syntax for disabling default plugins

---

.travis.yml
Project.toml
src/template.jl

Update version to 0.7.0

---

src/interactive.jl
test/interactive.jl

Fix interactive code for one-field types

---

src/plugins/ci.jl
test/fixtures/WackyOptions/.appveyor.yml
test/fixtures/WackyOptions/.cirrus.yml
test/fixtures/WackyOptions/.drone.star
test/fixtures/WackyOptions/.github/workflows/ci.yml
test/fixtures/WackyOptions/.gitlab-ci.yml
test/fixtures/WackyOptions/.travis.yml
test/plugin.jl
test/reference.jl

Don't include versions lower than the minimum in CI suites

---

Project.toml
src/PkgTemplates.jl
src/plugins/git.jl
test/git.jl
test/show.jl

Allow setting custom default branch name

---

Project.toml
src/plugins/documenter.jl
test/show.jl

Add default constructor for Documenter

---

docs/src/user.md

Escape: $ --> \$

---

.github/workflows/ci.yml

Allow test failures on Julia nightly

---

src/plugins/git.jl
test/fixtures/AllPlugins/.gitignore
test/fixtures/AllPlugins/docs/Manifest.toml
test/fixtures/Basic/.gitignore
test/fixtures/DocumenterGitHubActions/.gitignore
test/fixtures/DocumenterGitHubActions/docs/Manifest.toml
test/fixtures/DocumenterTravis/.gitignore
test/fixtures/DocumenterTravis/docs/Manifest.toml

Fix Manifest.toml entry in gitignore

---

templates/docs/make.jl
templates/github/workflows/ci.yml
templates/travis.yml
test/fixtures/AllPlugins/docs/make.jl
test/fixtures/DocumenterGitHubActions/.github/workflows/ci.yml
test/fixtures/DocumenterGitHubActions/docs/make.jl
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/DocumenterTravis/docs/make.jl
test/fixtures/WackyOptions/docs/make.jl

Add doc meta.setdocmeta by default

---

.github/workflows/CI.yml
.github/workflows/CompatHelper.yml
.github/workflows/JuliaNightly.yml
README.md
src/plugins/documenter.jl
test/runtests.jl

This pull request sets up the GitHubActions workflow on this repository. cc: @fchorney

MassInstallAction: Install the GitHubActions workflow on this repository

---

Project.toml

- seems no release has been made since v7.13
- let's make a single release with all the non-breaking changes since then

Increment to next non-breaking version

---

README.md

Please consider adding this function to the top of the README. Most newcomers get lost with a manual creation of the template.

Document generate_interactive

---

src/plugins/tagbot.jl

Fix a minor typo in tagbot.jl

---

Project.toml
src/plugins/project_file.jl
templates/CITATION.bib
test/fixtures/AllPlugins/CITATION.bib
test/fixtures/AllPlugins/Project.toml
test/fixtures/AllPlugins/docs/Manifest.toml
test/fixtures/Basic/Project.toml
test/fixtures/DocumenterGitHubActions/Project.toml
test/fixtures/DocumenterGitHubActions/docs/Manifest.toml
test/fixtures/DocumenterGitLabCI/Project.toml
test/fixtures/DocumenterGitLabCI/docs/Manifest.toml
test/fixtures/DocumenterTravis/Project.toml
test/fixtures/DocumenterTravis/docs/Manifest.toml
test/fixtures/WackyOptions/CITATION.bib
test/show.jl

Will close #387 
Some tests need amending, I am going to let CI tell me which

Start from v1.0.0-DEV

---

templates/github/workflows/TagBot.yml
test/fixtures/AllPlugins/.github/workflows/TagBot.yml
test/fixtures/Basic/.github/workflows/TagBot.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/TagBot.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/TagBot.yml
test/fixtures/DocumenterTravis/.github/workflows/TagBot.yml
test/fixtures/WackyOptions/.github/workflows/TagBot.yml

Update TagBot template

---

templates/github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

Makes for a cleaner GitHub action workflow

Use Julia shell in GitHub actions

---

test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

Fix reference tests that were broken by #441

Add permissions to fixture CI files

---

test/interactive.jl

Partial answer for #434 until we fix it

Mark broken interactive test as broken

---

src/plugins/documenter.jl
templates/github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/WackyOptions/.github/workflows/CI.yml

Add Documenter key and warning about SSH setup

---

README.md

This switches the demo in the README from Travis to GitHubActions

README.md: Travis -> GHA

---

src/PkgTemplates.jl
src/plugins/ci.jl
src/plugins/formatter.jl
templates/github/workflows/CI.yml
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/reference.jl

This simply adds runic-action to GH Actions CI

add Runic plugin

---

src/template.jl
test/fixtures/AllPlugins/.appveyor.yml
test/fixtures/AllPlugins/.cirrus.yml
test/fixtures/AllPlugins/.drone.star
test/fixtures/AllPlugins/.github/workflows/CI.yml
test/fixtures/AllPlugins/.gitlab-ci.yml
test/fixtures/AllPlugins/.travis.yml
test/fixtures/AllPlugins/Project.toml
test/fixtures/Basic/.github/workflows/CI.yml
test/fixtures/Basic/Project.toml
test/fixtures/DocumenterGitHubActions/.github/workflows/CI.yml
test/fixtures/DocumenterGitHubActions/Project.toml
test/fixtures/DocumenterGitLabCI/.github/workflows/CI.yml
test/fixtures/DocumenterGitLabCI/.gitlab-ci.yml
test/fixtures/DocumenterGitLabCI/Project.toml
test/fixtures/DocumenterTravis/.github/workflows/CI.yml
test/fixtures/DocumenterTravis/.travis.yml
test/fixtures/DocumenterTravis/Project.toml
test/fixtures/WackyOptions/.github/workflows/CI.yml
test/show.jl

Use newer LTS version from julialang website

Update minimum Julia version in template.jl
